### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by krahal** [sjason19/Senti#6]
Hey I'm checking out master and I keep getting this error on every website I visit with Senti on: 
<img width="648" alt="screen shot 2018-09-18 at 10 12 22 am" src="https://user-images.githubusercontent.com/21186730/45704355-825e3500-bb2b-11e8-878d-a8ca2e387d42.png">

**Comment by DConnorFong** [comment]
Fixed with [be91d89](https://github.com/sjason19/Senti/pull/7)
